disable_response_storage = true
model = "gpt-5-codex"
model_provider = "custom"
model_reasoning_effort = "high"

[model_providers.custom]
base_url = "https://icode.51talk.biz/v1"
name = "custom"
requires_openai_auth = true
wire_api = "responses"