"""add_preferred_language_to_users

Revision ID: f14db0738bba
Revises: c83b80768b59
Create Date: 2025-10-25 11:39:32.087225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14db0738bba'
down_revision: Union[str, None] = 'c83b80768b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加preferred_language字段到users表
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), server_default='zh_CN', nullable=False))

    # 添加检查约束确保只支持zh_CN和en_US
    op.create_check_constraint(
        'check_preferred_language',
        'users',
        "preferred_language IN ('zh_CN', 'en_US')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除检查约束
    op.drop_constraint('check_preferred_language', 'users', type_='check')

    # 删除preferred_language字段
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###